// <auto-generated>
// Generated by SRC/tools/gen-sintran-errors.py from NDIX systemerrors.h
// (NDIX release 3, "@(#) systemerrors.h 3.1 88/08/12").
// Texts and dispositions are ND's own, copied verbatim. Do not edit by hand.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{
    /// <summary>
    /// SINTRAN III file-system error numbers, with ND's own text and recovery advice.
    /// </summary>
    /// <remarks>
    /// <para><b>Why these matter here</b></para>
    /// A COSMOS file-access reply carries its failure as one of these numbers, and the
    /// calling machine prints it through SINTRAN's own table. So a status we SEND is read
    /// through this list at the far end, and a status we RECEIVE can only be explained by
    /// it. Before this existed a captured refusal was just a number in a log.
    /// <para><b>Source</b></para>
    /// NDIX release 3's <c>systemerrors.h</c>, a second and independent implementation of
    /// the same protocol family - so this is ND's classification, not our reading of it.
    /// </remarks>
    public static class SintranErrors
    {
        /// <summary>
        /// ND's text for each code, indexed by the code itself.
        /// </summary>
        private static readonly string[] Texts =
        {
            "ERROR CODE OUTSIDE RANGE",   // 0
            "ERROR CODE OUTSIDE RANGE",   // 1
            "BAD FILE NUMBER",   // 2
            "END OF FILE",   // 3
            "CARD READER ERROR (CARD READ)",   // 4
            "DEVICE NOT RESERVED",   // 5
            "ERROR CODE OUTSIDE RANGE",   // 6
            "CARD READER ERROR (CARD NOT READ)",   // 7
            "ERROR CODE OUTSIDE RANGE",   // 8
            "ERROR CODE OUTSIDE RANGE",   // 9
            "END OF DEVICE (TIMEOUT)",   // 10
            "ERROR CODE OUTSIDE RANGE",   // 11
            "ERROR CODE OUTSIDE RANGE",   // 12
            "ERROR CODE OUTSIDE RANGE",   // 13
            "ERROR CODE OUTSIDE RANGE",   // 14
            "ERROR CODE OUTSIDE RANGE",   // 15
            "ERROR CODE OUTSIDE RANGE",   // 16
            "ILLEGAL CHARACTER IN PARAMETER",   // 17
            "NO SUCH PAGE",   // 18
            "NOT DECIMAL NUMBER",   // 19
            "NOT OCTAL NUMBER",   // 20
            "YOU ARE NOT AUTHORIZED TO DO THIS",   // 21
            "DIRECTORY NOT ENTERED",   // 22
            "AMBIGUOUS DIRECTORY NAME",   // 23
            "NO SUCH DEVICE NAME",   // 24
            "AMBIGUOUS DEVICE NAME",   // 25
            "DIRECTORY ENTERED",   // 26
            "NO SUCH LOGICAL UNIT",   // 27
            "UNIT OCCUPIED",   // 28
            "MASTER BLOCK TRANSFER ERROR",   // 29
            "BIT-FILE TRANSFER ERROR",   // 30
            "NO MORE TRACKS AVAILABLE",   // 31
            "DIRECTORY NOT ON SPECIFIED UNIT",   // 32
            "FILES OPEN ON THIS DIRECTORY",   // 33
            "MAIN DIRECTORY NOT LAST ONE RELEASED",   // 34
            "NO MAIN DIRECTORY",   // 35
            "TOO LONG PARAMETER",   // 36
            "AMBIGUOUS USER NAME",   // 37
            "NO SUCH USER NAME",   // 38
            "NO SUCH USER NAME IN MAIN DIRECTORY",   // 39
            "ATTEMPT TO CREATE TOO MANY USERS",   // 40
            "USER ALREADY EXISTS",   // 41
            "USER HAS FILES",   // 42
            "USER IS ENTERED",   // 43
            "NOT SO MUCH SPACE UNRESERVED IN DIRECTORY",   // 44
            "RESERVED SPACE ALREADY USED",   // 45
            "NO SUCH FILE NAME",   // 46
            "AMBIGUOUS FILE NAME",   // 47
            "WRONG PASSWORD",   // 48
            "USER ALREADY ENTERED",   // 49
            "NO USER ENTERED",   // 50
            "FRIEND ALREADY EXISTS",   // 51
            "NO SUCH FRIEND",   // 52
            "ATTEMPT TO CREATE TOO MANY FRIENDS",   // 53
            "ATTEMPT TO CREATE YOURSELF AS FRIEND",   // 54
            "CONTIGUOUS SPACE NOT AVAILABLE",   // 55
            "NOT DIRECTORY ACCESS",   // 56
            "SPACE NOT AVAILABLE TO EXPAND FILE",   // 57
            "SPACE ALREADY ALLOCATED",   // 58
            "NO SPACE IN DEFAULT DIRECTORIES",   // 59
            "NO SUCH FILE VERSION",   // 60
            "NO MORE PAGES AVAILABLE FOR THIS USER",   // 61
            "FILE ALREADY EXISTS",   // 62
            "ATTEMPT TO CREATE TOO MANY FILES",   // 63
            "OUTSIDE DEVICE LIMITS",   // 64
            "NO PREVIOUS VERSION",   // 65
            "FILE NOT CONTIGUOUS",   // 66
            "FILE TYPE ALREADY DEFINED",   // 67
            "NO SUCH ACCESS CODE",   // 68
            "FILE ALREADY OPEN",   // 69
            "NOT WRITE ACCESS",   // 70
            "ATTEMPT TO OPEN TOO MANY FILES",   // 71
            "NOT WRITE AND APPEND ACCESS",   // 72
            "NOT READ ACCESS",   // 73
            "NOT READ, WRITE AND COMMON ACCESS",   // 74
            "NOT READ AND WRITE ACCESS",   // 75
            "NOT READ AND COMMON ACCESS",   // 76
            "FILE RESERVED BY ANOTHER USER",   // 77
            "FILE ALREADY OPENED FOR WRITE BY YOU",   // 78
            "NO SUCH USER INDEX",   // 79
            "NOT APPEND ACCESS",   // 80
            "ATTEMPT TO OPEN TOO MANY MASS STORAGE FILES",   // 81
            "ATTEMPT TO OPEN TOO MANY FILES",   // 82
            "NOT OPEN FOR SEQUENTIAL WRITE",   // 83
            "NOT OPEN FOR SEQUENTIAL READ",   // 84
            "NOT OPEN FOR RANDOM WRITE",   // 85
            "NOT OPEN FOR RANDOM READ",   // 86
            "FILE NUMBER OUT OF RANGE",   // 87
            "FILE NUMBER ALREADY USED",   // 88
            "NO MORE BUFFER SPACE",   // 89
            "NO FILE OPEN WITH THIS NUMBER",   // 90
            "NOT MASS STORAGE FILE",   // 91
            "FILE USED FOR WRITE",   // 92
            "FILE USED FOR READ",   // 93
            "FILE ONLY OPEN FOR SEQUENTIAL READ OR WRITE",   // 94
            "NO SCRATCH FILE OPEN",   // 95
            "FILE NOT RESERVED BY YOU",   // 96
            "TRANSFER ERROR",   // 97
            "FILE ALREADY RESERVED",   // 98
            "NO SUCH BLOCK",   // 99
            "SOURCE AND DESTINATION EQUAL",   // 100
            "ILLEGAL ON TAPE DEVICE",   // 101
            "END OF TAPE",   // 102
            "DEVICE UNIT RESERVED FOR SPECIAL USE",   // 103
            "MAIN DIRECTORY MUST BE DEFAULT",   // 104
            "NOT LAST FILE ON TAPE",   // 105
            "NOT TAPE DEVICE",   // 106
            "ILLEGAL ADDRESS REFERENCE IN MONITOR CALL",   // 107
            "SOURCE EMPTY",   // 108
            "FILE ALREADY OPENED BY ANOTHER USER",   // 109
            "FILE ALREADY OPENED FOR WRITE BY ANOTHER USER",   // 110
            "MISSING PARAMETER",   // 111
            "TWO PAGES MUST BE LEFT UNRESERVED",   // 112
            "",   // 113
            "DEVICE CANNOT BE RESERVED",   // 114
            "OVERFLOW IN READ",   // 115
            "DMA ERROR",   // 116
            "BAD DATA BLOCK",   // 117
            "CONTROL/MODUS WORD ERROR",   // 118
            "PARITY ERROR",   // 119
            "LRC ERROR",   // 120
            "DEVICE ERROR (DEVICE-FUNCTION READ-LAST-STATUS TO GET STATUS)",   // 121
            "DEVICE BUFFER OF REQUESTED SIZE NOT AVAILABLE",   // 122
            "ILLEGAL MASS STORAGE UNIT NUMBER",   // 123
            "ILLEGAL PARAMETER",   // 124
            "WRITE-PROTECT VIOLATION",   // 125
            "ERROR DETECTED BY READ AFTER WRITE",   // 126
            "NO EOF MARK FOUND",   // 127
            "ERROR CODE OUTSIDE RANGE",   // 128
            "ILLEGAL FUNCTION CODE",   // 129
            "TIMEOUT (NO DATA BLOCK FOUND)",   // 130
            "PAPER FAULT",   // 131
            "DEVICE NOT READY",   // 132
            "DEVICE ALREADY RESERVED",   // 133
            "NOT PERIPHERAL FILE",   // 134
            "NO SUCH QUEUE ENTRY",   // 135
            "NOT SO MUCH SPACE LEFT",   // 136
            "NO SPOOLING FOR THIS DEVICE",   // 137
            "NO SUCH QUEUE",   // 138
            "QUEUE EMPTY",   // 139
            "QUEUE FULL",   // 140
            "NOT LAST USED BY YOU",   // 141
            "",   // 142
            "",   // 143
            "",   // 144
            "",   // 145
            "",   // 146
            "FORMATTING ERROR",   // 147
            "INCOMPATIBLE DEVICE SIZES",   // 148
            "",   // 149
            "TAPE FORMAT ERROR",   // 150
            "BLOCK COUNT ERROR",   // 151
            "VOLUME NOT ON SPECIFIED UNIT",   // 152
            "NOT DELETED RECORD",   // 153
            "DEVICE ERROR",   // 154
            "ERROR IN OBJECT ENTRY",   // 155
            "ODD NUMBER OF BYTES (RIGHT BYTE IN LAST WORD INSIGNIFICANT)",   // 156
            "ERROR IN BACKSPACE/FORWARD-SPACE PRINT",   // 157
            "BLOCK FORMAT ERROR",   // 158
            "OVERFLOW IN WRITE",   // 159
            "ILLEGAL DEVICE TYPE",   // 160
            "SEGMENT NOT CONTIGUOUSLY FIXED",   // 161
            "SEGMENT NOT FIXED",   // 162
            "APPROACHING END OF ACCOUNTING FILE",   // 163
            "ACCOUNTING FILE FULL",   // 164
            "NO MORE UNUSED SPOOLING FILES AVAILABLE",   // 165
            "INCONSISTENT DIRECTORY",   // 166
            "OBJECT ENTRY NOT USED",   // 167
            "USER DOES NOT EXIST",   // 168
            "DIRECTORY NOT RESERVED",   // 169
            "NOT A MULTIPLE OF HARDWARE BLOCK SIZE",   // 170
            "NOT INDEXED FILE",   // 171
            "ILLEGAL FLOPPY FORMAT",   // 172
            "FILE NOT OPEN",   // 173
            "FILE ALREADY OPENED FOR READ OR WRITE BY YOU",   // 174
            "USER DOES NOT EXIST IN THE SAME MAIN DIRECTORY AS YOU",   // 175
            "FILE-ACCESS REENTRANT SEGMENTS NOT LOADED",   // 176
            "ILLEGAL ACCESS CODE FOR REMOTE FILE",   // 177
            "FILE-ACCESS CONNECTION ABORTED BY FILE SERVER",   // 178
            "FILE-ACCESS CONNECTION ABORTED BY FILE SERVER ADMINISTRATOR",   // 179
            "NO ANSWER FROM REMOTE SYSTEM; FILE-ACCESS CONNECTION ABORTED",   // 180
            "FILE-ACCESS INITIALIZATION FAILED",   // 181
            "UNKNOWN REMOTE SYSTEM NAME",   // 182
            "FILE-ACCESS PROTOCOL ERROR; CONNECTION ABORTED",   // 183
            "FILE-ACCESS INTERNAL ERROR; CALL NOT VALID IN CURRENT STATE",   // 184
            "ILLEGAL RANGE OF LAMU IDENTIFIER",   // 185
            "LAMU IN USE",   // 186
            "LAMU TABLE FULL",   // 187
            "ILLEGAL RT-PROGRAM",   // 188
            "MAXIMUM NUMBER OF LAMUS PER RT-PROGRAM REACHED",   // 189
            "LAMU NOT CONNECTED",   // 190
            "NO LAMU AREA BIG ENOUGH",   // 191
            "LAMU NOT DEFINED",   // 192
            "ILLEGAL LOGICAL PAGE NUMBER",   // 193
            "LOGICAL LAMU OVERLAP",   // 194
            "CAN ONLY LOG IN ON A MAIN DIRECTORY",   // 195
            "DIRECTORY INDEX TOO LARGE",   // 196
            "OBJECT INDEX TOO LARGE",   // 197
            "",   // 198
            "WARNING; 2-BANK PROG. FILE, BUT SEGMENT IS ONLY 1-BANK",   // 199
            "WARNING; NO SUCH PAGE IN DATA BANK, PROGRAM STARTS AS 1-BANK",   // 200
            "THE SPECIFIED DEVICE IS NOT A TERMINAL",   // 201
            "NO TERMINATION HANDLING DEFINED",   // 202
            "NO MORE REMOTE FILE-ACCESS DATA SEGMENTS AVAILABLE",   // 203
            "INPUT WHILE ESCAPE/LOCAL OFF IS ILLEGAL",   // 204
            "TAD PROTOCOL ERROR, ILLEGAL OR INCONSISTENT MESSAGE",   // 205
            "TERMINAL LINE IS NOT CONNECTED",   // 206
            "ILLEGAL COMBINATION OF DENTE AND DTUSE BITS",   // 207
            "DIRECTORY NOT RESERVED BY YOU",   // 208
            "WRONG PROJECT PASSWORD",   // 209
            "FILE-ACCESS TRANSPORT LAYER ERROR; ALL CONNECTIONS ABORTED",   // 210
            "FILE-ACCESS INTERNAL ERROR; INVALID PARAMETER VALUE",   // 211
            "FILE-ACCESS NOT RUNNING OR CRASHED; ALL CONNECTIONS ABORTED",   // 212
            "WRONG FORMAT IN FILE",   // 213
            "DIRECTORY ALREADY RESERVED FOR SPECIAL USE",   // 214
            "UNKNOWN USER-CONTROL CODE",   // 215
            "NO SERVICE IS AVAILABLE FOR THIS CODE",   // 216
            "PLEASE TERMINATE CURRENT SERVICE BEFORE REQUESTING NEW SERVICE",   // 217
            "THIS CODE IS ONLY LEGAL WITHIN A SERVICE",   // 218
            "REMOTE FILE SERVER IS NOT AVAILABLE",   // 219
            "ND-100 PANEL CLOCK INCORRECT",   // 220
            "BLOCK SIZE TOO BIG FOR BUFFER PREVIOUSLY OBTAINED",   // 221
            "ILLEGAL SEGMENT NAME",   // 222
            "NOT OCTAL NUMBER",   // 223
            "NOT CONTIGUOUS FILE",   // 224
            "AMBIGUOUS COMMAND",   // 225
            "PROTECTED COMMAND",   // 226
            "AMBIGUOUS SUBSYSTEM",   // 227
            "NO MORE SPOOLING PAGES LEFT",   // 228
            "NO MORE VERSIONS CAN BE CREATED IN THIS OBJECT BLOCK",   // 229
            "ILLEGAL BAUD RATE SPECIFIED",   // 230
            "ILLEGAL CHARACTER LENGTH",   // 231
            "ILLEGAL PARITY SPECIFIED",   // 232
            "NOT LEGAL FROM RT-PROGRAM",   // 233
            "ILLEGAL WHEN NOT ORIGINALLY OWN TERMINAL",   // 234
            "ILLEGAL BREAK/ECHO STRATEGY",   // 235
            "ILLEGAL SIZE OF PARAMETER ARRAY",   // 236
            "ILLEGAL AREA SPECIFIED",   // 237
            "NOT 8 BITS CHARACTER LENGTH",   // 238
            "TERMINAL ALREADY IN A DISPLAY TABLE",   // 239
            "NOT A MASTER TERMINAL",   // 240
            "NOT CONNECTED TO SPECIFIED MASTER TERMINAL",   // 241
            "ERROR IN DISPLAY TABLE",   // 242
            "FATAL ERROR OCCURED DURING READ/WRITE IN SEGMENTS",   // 243
            "BAUD RATE NOT SET BY SOFTWARE",   // 244
            "ILLEGAL BAUD RATE IN DATA FIELD",   // 245
            "TERMINAL IS ACTIVE",   // 246
            "NO MORE PHYSICAL MEMORY AVAILABLE",   // 247
            "NO MORE ALLOCATE-MEMORY-TABLE INDEXES AVAILABLE",   // 248
            "ILLEGAL SEGMENT",   // 249
            "ILLEGAL ADDRESS",   // 250
            "ILLEGAL PROGRAM LAMU IDENTIFIER",   // 251
            "PROGRAM LAMU ALREADY EXISTS",   // 252
            "NO SUCH PROGRAM LAMU",   // 253
            "ILLEGAL PROGRAM LAMU SIZE",   // 254
            "PROGRAM LAMU NOT CONNECTED",   // 255
        };

        /// <summary>
        /// ND's recovery disposition for each code, indexed by the code itself.
        /// </summary>
        private static readonly XmsgErrorDisposition[] Dispositions =
        {
            XmsgErrorDisposition.Retry,   // 0
            XmsgErrorDisposition.Retry,   // 1
            XmsgErrorDisposition.Retry,   // 2
            XmsgErrorDisposition.Retry,   // 3
            XmsgErrorDisposition.Retry,   // 4
            XmsgErrorDisposition.Retry,   // 5
            XmsgErrorDisposition.Retry,   // 6
            XmsgErrorDisposition.Retry,   // 7
            XmsgErrorDisposition.Retry,   // 8
            XmsgErrorDisposition.Retry,   // 9
            XmsgErrorDisposition.Retry,   // 10
            XmsgErrorDisposition.Retry,   // 11
            XmsgErrorDisposition.Retry,   // 12
            XmsgErrorDisposition.Retry,   // 13
            XmsgErrorDisposition.Retry,   // 14
            XmsgErrorDisposition.Retry,   // 15
            XmsgErrorDisposition.Retry,   // 16
            XmsgErrorDisposition.GiveUp,   // 17
            XmsgErrorDisposition.Retry,   // 18
            XmsgErrorDisposition.GiveUp,   // 19
            XmsgErrorDisposition.GiveUp,   // 20
            XmsgErrorDisposition.GiveUp,   // 21
            XmsgErrorDisposition.GiveUp,   // 22
            XmsgErrorDisposition.GiveUp,   // 23
            XmsgErrorDisposition.GiveUp,   // 24
            XmsgErrorDisposition.GiveUp,   // 25
            XmsgErrorDisposition.Retry,   // 26
            XmsgErrorDisposition.GiveUp,   // 27
            XmsgErrorDisposition.Retry,   // 28
            XmsgErrorDisposition.Retry,   // 29
            XmsgErrorDisposition.Retry,   // 30
            XmsgErrorDisposition.Retry,   // 31
            XmsgErrorDisposition.GiveUp,   // 32
            XmsgErrorDisposition.Retry,   // 33
            XmsgErrorDisposition.Retry,   // 34
            XmsgErrorDisposition.Retry,   // 35
            XmsgErrorDisposition.GiveUp,   // 36
            XmsgErrorDisposition.GiveUp,   // 37
            XmsgErrorDisposition.GiveUp,   // 38
            XmsgErrorDisposition.GiveUp,   // 39
            XmsgErrorDisposition.Retry,   // 40
            XmsgErrorDisposition.Retry,   // 41
            XmsgErrorDisposition.Retry,   // 42
            XmsgErrorDisposition.Retry,   // 43
            XmsgErrorDisposition.Retry,   // 44
            XmsgErrorDisposition.Retry,   // 45
            XmsgErrorDisposition.GiveUp,   // 46
            XmsgErrorDisposition.GiveUp,   // 47
            XmsgErrorDisposition.GiveUp,   // 48
            XmsgErrorDisposition.Retry,   // 49
            XmsgErrorDisposition.Retry,   // 50
            XmsgErrorDisposition.Retry,   // 51
            XmsgErrorDisposition.Retry,   // 52
            XmsgErrorDisposition.Retry,   // 53
            XmsgErrorDisposition.Retry,   // 54
            XmsgErrorDisposition.Retry,   // 55
            XmsgErrorDisposition.Retry,   // 56
            XmsgErrorDisposition.Retry,   // 57
            XmsgErrorDisposition.Retry,   // 58
            XmsgErrorDisposition.Retry,   // 59
            XmsgErrorDisposition.GiveUp,   // 60
            XmsgErrorDisposition.Retry,   // 61
            XmsgErrorDisposition.Retry,   // 62
            XmsgErrorDisposition.Retry,   // 63
            XmsgErrorDisposition.Retry,   // 64
            XmsgErrorDisposition.Retry,   // 65
            XmsgErrorDisposition.Retry,   // 66
            XmsgErrorDisposition.Retry,   // 67
            XmsgErrorDisposition.Retry,   // 68
            XmsgErrorDisposition.Retry,   // 69
            XmsgErrorDisposition.Retry,   // 70
            XmsgErrorDisposition.Retry,   // 71
            XmsgErrorDisposition.Retry,   // 72
            XmsgErrorDisposition.Retry,   // 73
            XmsgErrorDisposition.Retry,   // 74
            XmsgErrorDisposition.Retry,   // 75
            XmsgErrorDisposition.Retry,   // 76
            XmsgErrorDisposition.Retry,   // 77
            XmsgErrorDisposition.Retry,   // 78
            XmsgErrorDisposition.Retry,   // 79
            XmsgErrorDisposition.Retry,   // 80
            XmsgErrorDisposition.Retry,   // 81
            XmsgErrorDisposition.Retry,   // 82
            XmsgErrorDisposition.Retry,   // 83
            XmsgErrorDisposition.Retry,   // 84
            XmsgErrorDisposition.Retry,   // 85
            XmsgErrorDisposition.Retry,   // 86
            XmsgErrorDisposition.Retry,   // 87
            XmsgErrorDisposition.Retry,   // 88
            XmsgErrorDisposition.Retry,   // 89
            XmsgErrorDisposition.Retry,   // 90
            XmsgErrorDisposition.Retry,   // 91
            XmsgErrorDisposition.Retry,   // 92
            XmsgErrorDisposition.Retry,   // 93
            XmsgErrorDisposition.Retry,   // 94
            XmsgErrorDisposition.Retry,   // 95
            XmsgErrorDisposition.Retry,   // 96
            XmsgErrorDisposition.Retry,   // 97
            XmsgErrorDisposition.Retry,   // 98
            XmsgErrorDisposition.Retry,   // 99
            XmsgErrorDisposition.Retry,   // 100
            XmsgErrorDisposition.Retry,   // 101
            XmsgErrorDisposition.Retry,   // 102
            XmsgErrorDisposition.Retry,   // 103
            XmsgErrorDisposition.Retry,   // 104
            XmsgErrorDisposition.Retry,   // 105
            XmsgErrorDisposition.Retry,   // 106
            XmsgErrorDisposition.Retry,   // 107
            XmsgErrorDisposition.GiveUp,   // 108
            XmsgErrorDisposition.Retry,   // 109
            XmsgErrorDisposition.Retry,   // 110
            XmsgErrorDisposition.Retry,   // 111
            XmsgErrorDisposition.Retry,   // 112
            XmsgErrorDisposition.Retry,   // 113
            XmsgErrorDisposition.Retry,   // 114
            XmsgErrorDisposition.Retry,   // 115
            XmsgErrorDisposition.Retry,   // 116
            XmsgErrorDisposition.Retry,   // 117
            XmsgErrorDisposition.Retry,   // 118
            XmsgErrorDisposition.Retry,   // 119
            XmsgErrorDisposition.Retry,   // 120
            XmsgErrorDisposition.Retry,   // 121
            XmsgErrorDisposition.Retry,   // 122
            XmsgErrorDisposition.Retry,   // 123
            XmsgErrorDisposition.Retry,   // 124
            XmsgErrorDisposition.Retry,   // 125
            XmsgErrorDisposition.Retry,   // 126
            XmsgErrorDisposition.Retry,   // 127
            XmsgErrorDisposition.Retry,   // 128
            XmsgErrorDisposition.Retry,   // 129
            XmsgErrorDisposition.Retry,   // 130
            XmsgErrorDisposition.Retry,   // 131
            XmsgErrorDisposition.Retry,   // 132
            XmsgErrorDisposition.Retry,   // 133
            XmsgErrorDisposition.Retry,   // 134
            XmsgErrorDisposition.Retry,   // 135
            XmsgErrorDisposition.Retry,   // 136
            XmsgErrorDisposition.Retry,   // 137
            XmsgErrorDisposition.Retry,   // 138
            XmsgErrorDisposition.Retry,   // 139
            XmsgErrorDisposition.Retry,   // 140
            XmsgErrorDisposition.Retry,   // 141
            XmsgErrorDisposition.Retry,   // 142
            XmsgErrorDisposition.Retry,   // 143
            XmsgErrorDisposition.Retry,   // 144
            XmsgErrorDisposition.Retry,   // 145
            XmsgErrorDisposition.Retry,   // 146
            XmsgErrorDisposition.Retry,   // 147
            XmsgErrorDisposition.Retry,   // 148
            XmsgErrorDisposition.Retry,   // 149
            XmsgErrorDisposition.Retry,   // 150
            XmsgErrorDisposition.Retry,   // 151
            XmsgErrorDisposition.Retry,   // 152
            XmsgErrorDisposition.Retry,   // 153
            XmsgErrorDisposition.Retry,   // 154
            XmsgErrorDisposition.Retry,   // 155
            XmsgErrorDisposition.Retry,   // 156
            XmsgErrorDisposition.Retry,   // 157
            XmsgErrorDisposition.Retry,   // 158
            XmsgErrorDisposition.Retry,   // 159
            XmsgErrorDisposition.Retry,   // 160
            XmsgErrorDisposition.Retry,   // 161
            XmsgErrorDisposition.Retry,   // 162
            XmsgErrorDisposition.Retry,   // 163
            XmsgErrorDisposition.Retry,   // 164
            XmsgErrorDisposition.Retry,   // 165
            XmsgErrorDisposition.Retry,   // 166
            XmsgErrorDisposition.Retry,   // 167
            XmsgErrorDisposition.Retry,   // 168
            XmsgErrorDisposition.Retry,   // 169
            XmsgErrorDisposition.Retry,   // 170
            XmsgErrorDisposition.Retry,   // 171
            XmsgErrorDisposition.Retry,   // 172
            XmsgErrorDisposition.Retry,   // 173
            XmsgErrorDisposition.Retry,   // 174
            XmsgErrorDisposition.Retry,   // 175
            XmsgErrorDisposition.Retry,   // 176
            XmsgErrorDisposition.Retry,   // 177
            XmsgErrorDisposition.Retry,   // 178
            XmsgErrorDisposition.Retry,   // 179
            XmsgErrorDisposition.Suspend,   // 180
            XmsgErrorDisposition.Retry,   // 181
            XmsgErrorDisposition.Retry,   // 182
            XmsgErrorDisposition.Retry,   // 183
            XmsgErrorDisposition.Retry,   // 184
            XmsgErrorDisposition.Retry,   // 185
            XmsgErrorDisposition.Retry,   // 186
            XmsgErrorDisposition.Retry,   // 187
            XmsgErrorDisposition.Retry,   // 188
            XmsgErrorDisposition.Retry,   // 189
            XmsgErrorDisposition.Retry,   // 190
            XmsgErrorDisposition.Retry,   // 191
            XmsgErrorDisposition.Retry,   // 192
            XmsgErrorDisposition.Retry,   // 193
            XmsgErrorDisposition.Retry,   // 194
            XmsgErrorDisposition.Retry,   // 195
            XmsgErrorDisposition.Retry,   // 196
            XmsgErrorDisposition.Retry,   // 197
            XmsgErrorDisposition.Retry,   // 198
            XmsgErrorDisposition.Retry,   // 199
            XmsgErrorDisposition.Retry,   // 200
            XmsgErrorDisposition.Retry,   // 201
            XmsgErrorDisposition.Retry,   // 202
            XmsgErrorDisposition.Retry,   // 203
            XmsgErrorDisposition.Retry,   // 204
            XmsgErrorDisposition.Retry,   // 205
            XmsgErrorDisposition.Retry,   // 206
            XmsgErrorDisposition.Retry,   // 207
            XmsgErrorDisposition.Retry,   // 208
            XmsgErrorDisposition.Retry,   // 209
            XmsgErrorDisposition.Retry,   // 210
            XmsgErrorDisposition.Retry,   // 211
            XmsgErrorDisposition.Retry,   // 212
            XmsgErrorDisposition.Retry,   // 213
            XmsgErrorDisposition.Retry,   // 214
            XmsgErrorDisposition.Retry,   // 215
            XmsgErrorDisposition.Retry,   // 216
            XmsgErrorDisposition.Retry,   // 217
            XmsgErrorDisposition.Retry,   // 218
            XmsgErrorDisposition.Suspend,   // 219
            XmsgErrorDisposition.Retry,   // 220
            XmsgErrorDisposition.Retry,   // 221
            XmsgErrorDisposition.Retry,   // 222
            XmsgErrorDisposition.Retry,   // 223
            XmsgErrorDisposition.Retry,   // 224
            XmsgErrorDisposition.Retry,   // 225
            XmsgErrorDisposition.Retry,   // 226
            XmsgErrorDisposition.Retry,   // 227
            XmsgErrorDisposition.Retry,   // 228
            XmsgErrorDisposition.Retry,   // 229
            XmsgErrorDisposition.Retry,   // 230
            XmsgErrorDisposition.Retry,   // 231
            XmsgErrorDisposition.Retry,   // 232
            XmsgErrorDisposition.Retry,   // 233
            XmsgErrorDisposition.Retry,   // 234
            XmsgErrorDisposition.Retry,   // 235
            XmsgErrorDisposition.Retry,   // 236
            XmsgErrorDisposition.Retry,   // 237
            XmsgErrorDisposition.Retry,   // 238
            XmsgErrorDisposition.Retry,   // 239
            XmsgErrorDisposition.Retry,   // 240
            XmsgErrorDisposition.Retry,   // 241
            XmsgErrorDisposition.Retry,   // 242
            XmsgErrorDisposition.Retry,   // 243
            XmsgErrorDisposition.Retry,   // 244
            XmsgErrorDisposition.Retry,   // 245
            XmsgErrorDisposition.Retry,   // 246
            XmsgErrorDisposition.Retry,   // 247
            XmsgErrorDisposition.Retry,   // 248
            XmsgErrorDisposition.Retry,   // 249
            XmsgErrorDisposition.Retry,   // 250
            XmsgErrorDisposition.Retry,   // 251
            XmsgErrorDisposition.Retry,   // 252
            XmsgErrorDisposition.Retry,   // 253
            XmsgErrorDisposition.Retry,   // 254
            XmsgErrorDisposition.Retry,   // 255
        };

        /// <summary>
        /// True where ND's table gives the code a real meaning rather than filler.
        /// </summary>
        /// <remarks>
        /// ND fills the unused numbers with a single placeholder text. Recorded separately so
        /// a caller can tell "there is no such error" from a genuine one.
        /// </remarks>
        private static readonly bool[] Meaningful =
        {
            false,   // 0
            false,   // 1
            true,   // 2
            true,   // 3
            true,   // 4
            true,   // 5
            false,   // 6
            true,   // 7
            false,   // 8
            false,   // 9
            true,   // 10
            false,   // 11
            false,   // 12
            false,   // 13
            false,   // 14
            false,   // 15
            false,   // 16
            true,   // 17
            true,   // 18
            true,   // 19
            true,   // 20
            true,   // 21
            true,   // 22
            true,   // 23
            true,   // 24
            true,   // 25
            true,   // 26
            true,   // 27
            true,   // 28
            true,   // 29
            true,   // 30
            true,   // 31
            true,   // 32
            true,   // 33
            true,   // 34
            true,   // 35
            true,   // 36
            true,   // 37
            true,   // 38
            true,   // 39
            true,   // 40
            true,   // 41
            true,   // 42
            true,   // 43
            true,   // 44
            true,   // 45
            true,   // 46
            true,   // 47
            true,   // 48
            true,   // 49
            true,   // 50
            true,   // 51
            true,   // 52
            true,   // 53
            true,   // 54
            true,   // 55
            true,   // 56
            true,   // 57
            true,   // 58
            true,   // 59
            true,   // 60
            true,   // 61
            true,   // 62
            true,   // 63
            true,   // 64
            true,   // 65
            true,   // 66
            true,   // 67
            true,   // 68
            true,   // 69
            true,   // 70
            true,   // 71
            true,   // 72
            true,   // 73
            true,   // 74
            true,   // 75
            true,   // 76
            true,   // 77
            true,   // 78
            true,   // 79
            true,   // 80
            true,   // 81
            true,   // 82
            true,   // 83
            true,   // 84
            true,   // 85
            true,   // 86
            true,   // 87
            true,   // 88
            true,   // 89
            true,   // 90
            true,   // 91
            true,   // 92
            true,   // 93
            true,   // 94
            true,   // 95
            true,   // 96
            true,   // 97
            true,   // 98
            true,   // 99
            true,   // 100
            true,   // 101
            true,   // 102
            true,   // 103
            true,   // 104
            true,   // 105
            true,   // 106
            true,   // 107
            true,   // 108
            true,   // 109
            true,   // 110
            true,   // 111
            true,   // 112
            true,   // 113
            true,   // 114
            true,   // 115
            true,   // 116
            true,   // 117
            true,   // 118
            true,   // 119
            true,   // 120
            true,   // 121
            true,   // 122
            true,   // 123
            true,   // 124
            true,   // 125
            true,   // 126
            true,   // 127
            false,   // 128
            true,   // 129
            true,   // 130
            true,   // 131
            true,   // 132
            true,   // 133
            true,   // 134
            true,   // 135
            true,   // 136
            true,   // 137
            true,   // 138
            true,   // 139
            true,   // 140
            true,   // 141
            true,   // 142
            true,   // 143
            true,   // 144
            true,   // 145
            true,   // 146
            true,   // 147
            true,   // 148
            true,   // 149
            true,   // 150
            true,   // 151
            true,   // 152
            true,   // 153
            true,   // 154
            true,   // 155
            true,   // 156
            true,   // 157
            true,   // 158
            true,   // 159
            true,   // 160
            true,   // 161
            true,   // 162
            true,   // 163
            true,   // 164
            true,   // 165
            true,   // 166
            true,   // 167
            true,   // 168
            true,   // 169
            true,   // 170
            true,   // 171
            true,   // 172
            true,   // 173
            true,   // 174
            true,   // 175
            true,   // 176
            true,   // 177
            true,   // 178
            true,   // 179
            true,   // 180
            true,   // 181
            true,   // 182
            true,   // 183
            true,   // 184
            true,   // 185
            true,   // 186
            true,   // 187
            true,   // 188
            true,   // 189
            true,   // 190
            true,   // 191
            true,   // 192
            true,   // 193
            true,   // 194
            true,   // 195
            true,   // 196
            true,   // 197
            true,   // 198
            true,   // 199
            true,   // 200
            true,   // 201
            true,   // 202
            true,   // 203
            true,   // 204
            true,   // 205
            true,   // 206
            true,   // 207
            true,   // 208
            true,   // 209
            true,   // 210
            true,   // 211
            true,   // 212
            true,   // 213
            true,   // 214
            true,   // 215
            true,   // 216
            true,   // 217
            true,   // 218
            true,   // 219
            true,   // 220
            true,   // 221
            true,   // 222
            true,   // 223
            true,   // 224
            true,   // 225
            true,   // 226
            true,   // 227
            true,   // 228
            true,   // 229
            true,   // 230
            true,   // 231
            true,   // 232
            true,   // 233
            true,   // 234
            true,   // 235
            true,   // 236
            true,   // 237
            true,   // 238
            true,   // 239
            true,   // 240
            true,   // 241
            true,   // 242
            true,   // 243
            true,   // 244
            true,   // 245
            true,   // 246
            true,   // 247
            true,   // 248
            true,   // 249
            true,   // 250
            true,   // 251
            true,   // 252
            true,   // 253
            true,   // 254
            true,   // 255
        };

        /// <summary>
        /// Gets the number of codes ND's table covers.
        /// </summary>
        public const int Count = 256;

        /// <summary>
        /// Returns ND's text for a SINTRAN error code.
        /// </summary>
        /// <param name="code">
        /// The error number as it travels on the wire.
        /// </param>
        /// <returns>
        /// ND's own wording, or a plain marker when the code is outside the table.
        /// </returns>
        public static string Describe(int code)
        {
            if (code < 0 || code >= Texts.Length)
            {
                return "(outside SINTRAN's error table)";
            }

            return Texts[code];
        }

        /// <summary>
        /// Returns ND's recovery disposition for a SINTRAN error code.
        /// </summary>
        /// <param name="code">
        /// The error number as it travels on the wire.
        /// </param>
        /// <returns>
        /// The disposition, or <see cref="XmsgErrorDisposition.Unknown"/> outside the table.
        /// </returns>
        public static XmsgErrorDisposition DispositionOf(int code)
        {
            if (code < 0 || code >= Dispositions.Length)
            {
                return XmsgErrorDisposition.Unknown;
            }

            return Dispositions[code];
        }

        /// <summary>
        /// Reports whether ND's table gives this code a real meaning.
        /// </summary>
        /// <param name="code">
        /// The error number as it travels on the wire.
        /// </param>
        /// <returns>
        /// False for a code outside the table, and for one ND fills with a placeholder.
        /// </returns>
        /// <remarks>
        /// Worth checking before choosing a code to SEND: a placeholder number makes a real
        /// machine print "ERROR CODE OUTSIDE RANGE", which tells the user nothing.
        /// </remarks>
        public static bool IsMeaningful(int code)
        {
            if (code < 0 || code >= Meaningful.Length)
            {
                return false;
            }

            return Meaningful[code];
        }
    }
}
