# -*- coding: utf-8 -*-
# Generator for the XMSG enum .cs files.
# Reads the AUTHORITATIVE xmsg-constants.json and emits one C# file per enum,
# with a 3-line /// <summary> per member taken verbatim from the official desc.
import json, os, io

# Paths are resolved relative to this script so the tool is portable (no absolute
# paths). Layout:  XMSG/xmsg-constants.json  and  XMSG/SRC/tools/gen-xmsg-enums.py
# -> the enum output lands in  XMSG/SRC/Xmsg.Protocol/Enums.
_HERE = os.path.dirname(os.path.abspath(__file__))          # XMSG/SRC/tools
XMSG  = os.path.abspath(os.path.join(_HERE, "..", ".."))    # XMSG (holds the JSON)
OUT   = os.path.join(_HERE, "..", "Xmsg.Protocol", "Enums") # XMSG/SRC/Xmsg.Protocol/Enums
os.makedirs(OUT, exist_ok=True)

with io.open(os.path.join(XMSG, "xmsg-constants.json"), "r", encoding="utf-8") as f:
    J = json.load(f)

def esc(s):
    # XML-escape for /// doc comments.
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def wrap_summary(desc, indent="    "):
    out = []
    out.append(indent + "/// <summary>")
    out.append(indent + "/// " + esc(desc))
    out.append(indent + "/// </summary>")
    return "\n".join(out)

def header():
    return ("// <auto-generated>\n"
            "// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).\n"
            "// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL\n"
            "// Descriptions are copied verbatim from the official ND include-file comments.\n"
            "// Do not edit by hand - regenerate from the JSON.\n"
            "// </auto-generated>\n\n"
            "namespace NDInsight.Sintran.Xmsg\n{\n")

def emit_plain(name, section, typedecl, type_summary, seen_alias_ok=True, value_transform=None):
    entries = J[section]
    lines = [header()]
    lines.append(wrap_summary(type_summary))
    lines.append("    public enum " + typedecl)
    lines.append("    {")
    seen = {}
    body = []
    for sym, obj in entries.items():
        v = obj["value"]
        if value_transform:
            vexpr = value_transform(v)
        else:
            vexpr = str(v)
        body.append(wrap_summary(obj["desc"], "        "))
        body.append("        " + sym + " = " + vexpr + ",")
        body.append("")
    if body and body[-1] == "":
        body.pop()
    lines.append("\n".join(body))
    lines.append("    }")
    lines.append("}")
    with io.open(os.path.join(OUT, name + ".cs"), "w", encoding="utf-8", newline="\r\n") as fo:
        fo.write("\n".join(lines) + "\n")

# ---- XmsgFunction (XF*) ----
emit_plain("XmsgFunction", "functions",
           "XmsgFunction : int",
           "XMSG function codes (XF*) placed in the MON 200B T-register low byte.")

# ---- XmsgDriverFunction (XD*) ----
emit_plain("XmsgDriverFunction", "driver_functions",
           "XmsgDriverFunction : int",
           "XMSG driver-interface functions (XD*, DRXMSG).")

# ---- XmsgMessageType (XM*) returned by XFRCV ----
emit_plain("XmsgMessageType", "message_types",
           "XmsgMessageType : int",
           "Message-type codes (XM*) returned by XFRCV in the T-register.")

# ---- XmsgError (XE*) negative ----
emit_plain("XmsgError", "user_errors",
           "XmsgError : int",
           "XMSG user error codes (XE*), returned negative in the T-register.")

# ---- XroutService (XS*) ----
emit_plain("XroutService", "xrout_services",
           "XroutService : int",
           "XROUT service codes (XS*), byte 1 of the standard-message header.")

# ---- XroutError (XR*) ----
emit_plain("XroutError", "xrout_errors",
           "XroutError : int",
           "XROUT / network-server error codes (XR*), byte 1 of a reply.")

# ---- XmfidoStatus ----
emit_plain("XmfidoStatus", "xmfido_status",
           "XmfidoStatus : int",
           "XMFIDO file-distribution status codes.")

# ---- XmsgCrashCode (XX*) ----
emit_plain("XmsgCrashCode", "crash_codes",
           "XmsgCrashCode : int",
           "XMSG kernel crash codes (XX*).")

# ---- XmsgOption ([Flags], values are BIT NUMBERS -> mask = 1 << bit) ----
def emit_options():
    entries = J["option_bits"]
    lines = [header()]
    lines.append("    /// <summary>")
    lines.append("    /// MON 200B T-register option bits, OR-ed into the high-order byte alongside")
    lines.append("    /// the function code. Each flag mask is <c>1 &lt;&lt; bit</c>.")
    lines.append("    /// </summary>")
    lines.append("    [System.Flags]")
    lines.append("    public enum XmsgOption : ushort")
    lines.append("    {")
    lines.append("        /// <summary>")
    lines.append("        /// No option bits set.")
    lines.append("        /// </summary>")
    lines.append("        None = 0,")
    lines.append("")
    body = []
    for sym, obj in entries.items():
        bit = obj["value"]
        mask = 1 << bit
        body.append("        /// <summary>")
        body.append("        /// " + esc(obj["desc"]))
        body.append("        /// </summary>")
        body.append("        /// <remarks>")
        body.append("        /// Bit " + str(bit) + " (mask 0x" + format(mask, "04X") + ") in the MON 200B T-register high byte.")
        body.append("        /// </remarks>")
        body.append("        " + sym + " = 1 << " + str(bit) + ",")
        body.append("")
    if body and body[-1] == "":
        body.pop()
    lines.append("\n".join(body))
    lines.append("    }")
    lines.append("}")
    with io.open(os.path.join(OUT, "XmsgOption.cs"), "w", encoding="utf-8", newline="\r\n") as fo:
        fo.write("\n".join(lines) + "\n")
emit_options()

# ---- XROUT sub-service enums (split by parent service to avoid value collisions) ----
# Groupings taken from XMSG-API.md section 6.4.
SUBGROUPS = {
    "XroutSetCrashInfoSubservice": (
        "Sub-service codes (parameter 1) for the XSSCI set-crash-information service.",
        ["XSDAR", "XSDRF", "XSDDF", "XSGDF", "XSDUX", "XSGRF", "XSGAR"]),
    "XroutGetAttributeSubservice": (
        "Sub-service codes (parameter 1) for the XSGAT get/check-attribute service.",
        ["XSGXV", "XSCMG", "XSGCN", "XSGFR", "XSGLO"]),
    "XroutDefineAttributeSubservice": (
        "Sub-service codes (parameter 1) for the XSDAT define/remove-attribute service.",
        ["XSDFR", "XSRFR", "XSECS", "XSDCS", "XSDAL"]),
}
def emit_subgroups():
    src = J["xrout_subservices"]
    for typename, (summary, syms) in SUBGROUPS.items():
        lines = [header()]
        lines.append(wrap_summary(summary))
        lines.append("    public enum " + typename + " : int")
        lines.append("    {")
        body = []
        for sym in syms:
            obj = src[sym]
            body.append(wrap_summary(obj["desc"], "        "))
            body.append("        " + sym + " = " + str(obj["value"]) + ",")
            body.append("")
        if body and body[-1] == "":
            body.pop()
        lines.append("\n".join(body))
        lines.append("    }")
        lines.append("}")
        with io.open(os.path.join(OUT, typename + ".cs"), "w", encoding="utf-8", newline="\r\n") as fo:
            fo.write("\n".join(lines) + "\n")
emit_subgroups()

print("Generated enum files in", OUT)
