#!/usr/bin/env python3
"""Generate SintranErrors.cs from NDIX's systemerrors.h.

WHY A GENERATOR AND NOT A HAND TRANSCRIPTION
--------------------------------------------
There are 256 codes. Typing them by hand would put a silent error somewhere in the
middle that no test would ever catch, because nothing else in this repository knows
what SINTRAN error 137 says. The source file IS the authority, so it is read.

SOURCE
------
E:\\Dev\\Ronny\\NDIX-C\\baseline\\bin\\cps\\systemerrors.h - NDIX release 3, stamped
"3.1 88/08/12". It holds two things:

  #define ERR30  "NO SUCH FILE NAME"     /* 046 */      <- macro to text
  46, ERR30, SIII_GIVE_UP,                              <- code to macro + disposition

The comment number on the #define is NOT trusted: the table at the bottom is what
maps a code to a macro, and a few #define comments disagree with it. Where they
differ the table wins, because the table is what NDIX itself indexes.

USAGE
-----
    python SRC/tools/gen-sintran-errors.py
"""

import re
import sys
from pathlib import Path

SOURCE = Path(r"E:\Dev\Ronny\NDIX-C\baseline\bin\cps\systemerrors.h")
TARGET = Path(__file__).resolve().parent.parent / "Xmsg.Protocol" / "Errors" / "SintranErrors.cs"

# ND's dispositions, mapped onto ours. Same names as the XMSG import already uses.
DISPOSITION = {
    "SIII_OK": "Ok",
    "SIII_RETRY": "Retry",
    "SIII_GIVE_UP": "GiveUp",
    "SIII_SUSPEND": "Suspend",
    "SIII_SLEEP": "Sleep",
    "SIII_UNKNOWN": "Unknown",
}

DEFINE_RE = re.compile(r'^#define\s+(\w+)\s+"([^"]*)"')
ROW_RE = re.compile(r'^\s*(\d+),\s*(\w+),\s*(SIII_\w+),')


def read_source(path):
    """Return (macro -> text, [(code, macro, disposition)])."""
    if not path.exists():
        sys.exit(f"source not found: {path}")

    texts = {}
    rows = []

    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = DEFINE_RE.match(line)
        if m:
            texts[m.group(1)] = m.group(2)
            continue

        m = ROW_RE.match(line)
        if m:
            rows.append((int(m.group(1)), m.group(2), m.group(3)))

    return texts, rows


def escape(text):
    """Escape a C# string literal. ND's texts are plain ASCII but contain no quotes today."""
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main():
    texts, rows = read_source(SOURCE)

    if not rows:
        sys.exit("no table rows parsed - has the file format changed?")

    highest = max(code for code, _, _ in rows)
    size = highest + 1

    # ERR0 is ND's own filler for codes that carry no meaning. Kept verbatim in the text
    # array, but flagged so a caller can tell "no such error" from a real one.
    filler_macro = "ERR0"

    entries = [None] * size
    for code, macro, disp in rows:
        entries[code] = (texts.get(macro, ""), DISPOSITION.get(disp, "Unknown"), macro)

    lines = []
    lines.append("// <auto-generated>")
    lines.append("// Generated by SRC/tools/gen-sintran-errors.py from NDIX systemerrors.h")
    lines.append('// (NDIX release 3, "@(#) systemerrors.h 3.1 88/08/12").')
    lines.append("// Texts and dispositions are ND's own, copied verbatim. Do not edit by hand.")
    lines.append("// </auto-generated>")
    lines.append("")
    lines.append("namespace NDInsight.Sintran.Xmsg")
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// SINTRAN III file-system error numbers, with ND's own text and recovery advice.")
    lines.append("    /// </summary>")
    lines.append("    /// <remarks>")
    lines.append("    /// <para><b>Why these matter here</b></para>")
    lines.append("    /// A COSMOS file-access reply carries its failure as one of these numbers, and the")
    lines.append("    /// calling machine prints it through SINTRAN's own table. So a status we SEND is read")
    lines.append("    /// through this list at the far end, and a status we RECEIVE can only be explained by")
    lines.append("    /// it. Before this existed a captured refusal was just a number in a log.")
    lines.append("    /// <para><b>Source</b></para>")
    lines.append("    /// NDIX release 3's <c>systemerrors.h</c>, a second and independent implementation of")
    lines.append("    /// the same protocol family - so this is ND's classification, not our reading of it.")
    lines.append("    /// </remarks>")
    lines.append("    public static class SintranErrors")
    lines.append("    {")
    lines.append("        /// <summary>")
    lines.append("        /// ND's text for each code, indexed by the code itself.")
    lines.append("        /// </summary>")
    lines.append("        private static readonly string[] Texts =")
    lines.append("        {")

    for code in range(size):
        entry = entries[code]
        text = entry[0] if entry else ""
        lines.append(f'            "{escape(text)}",   // {code}')

    lines.append("        };")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// ND's recovery disposition for each code, indexed by the code itself.")
    lines.append("        /// </summary>")
    lines.append("        private static readonly XmsgErrorDisposition[] Dispositions =")
    lines.append("        {")

    for code in range(size):
        entry = entries[code]
        disp = entry[1] if entry else "Unknown"
        lines.append(f"            XmsgErrorDisposition.{disp},   // {code}")

    lines.append("        };")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// True where ND's table gives the code a real meaning rather than filler.")
    lines.append("        /// </summary>")
    lines.append("        /// <remarks>")
    lines.append("        /// ND fills the unused numbers with a single placeholder text. Recorded separately so")
    lines.append("        /// a caller can tell \"there is no such error\" from a genuine one.")
    lines.append("        /// </remarks>")
    lines.append("        private static readonly bool[] Meaningful =")
    lines.append("        {")

    for code in range(size):
        entry = entries[code]
        real = "true" if entry and entry[2] != filler_macro else "false"
        lines.append(f"            {real},   // {code}")

    lines.append("        };")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Gets the number of codes ND's table covers.")
    lines.append("        /// </summary>")
    lines.append(f"        public const int Count = {size};")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Returns ND's text for a SINTRAN error code.")
    lines.append("        /// </summary>")
    lines.append("        /// <param name=\"code\">")
    lines.append("        /// The error number as it travels on the wire.")
    lines.append("        /// </param>")
    lines.append("        /// <returns>")
    lines.append("        /// ND's own wording, or a plain marker when the code is outside the table.")
    lines.append("        /// </returns>")
    lines.append("        public static string Describe(int code)")
    lines.append("        {")
    lines.append("            if (code < 0 || code >= Texts.Length)")
    lines.append("            {")
    lines.append("                return \"(outside SINTRAN's error table)\";")
    lines.append("            }")
    lines.append("")
    lines.append("            return Texts[code];")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Returns ND's recovery disposition for a SINTRAN error code.")
    lines.append("        /// </summary>")
    lines.append("        /// <param name=\"code\">")
    lines.append("        /// The error number as it travels on the wire.")
    lines.append("        /// </param>")
    lines.append("        /// <returns>")
    lines.append("        /// The disposition, or <see cref=\"XmsgErrorDisposition.Unknown\"/> outside the table.")
    lines.append("        /// </returns>")
    lines.append("        public static XmsgErrorDisposition DispositionOf(int code)")
    lines.append("        {")
    lines.append("            if (code < 0 || code >= Dispositions.Length)")
    lines.append("            {")
    lines.append("                return XmsgErrorDisposition.Unknown;")
    lines.append("            }")
    lines.append("")
    lines.append("            return Dispositions[code];")
    lines.append("        }")
    lines.append("")
    lines.append("        /// <summary>")
    lines.append("        /// Reports whether ND's table gives this code a real meaning.")
    lines.append("        /// </summary>")
    lines.append("        /// <param name=\"code\">")
    lines.append("        /// The error number as it travels on the wire.")
    lines.append("        /// </param>")
    lines.append("        /// <returns>")
    lines.append("        /// False for a code outside the table, and for one ND fills with a placeholder.")
    lines.append("        /// </returns>")
    lines.append("        /// <remarks>")
    lines.append("        /// Worth checking before choosing a code to SEND: a placeholder number makes a real")
    lines.append("        /// machine print \"ERROR CODE OUTSIDE RANGE\", which tells the user nothing.")
    lines.append("        /// </remarks>")
    lines.append("        public static bool IsMeaningful(int code)")
    lines.append("        {")
    lines.append("            if (code < 0 || code >= Meaningful.Length)")
    lines.append("            {")
    lines.append("                return false;")
    lines.append("            }")
    lines.append("")
    lines.append("            return Meaningful[code];")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")

    meaningful = sum(1 for e in entries if e and e[2] != filler_macro)
    print(f"wrote {TARGET}")
    print(f"  {size} codes, {meaningful} with a real meaning, {size - meaningful} filler")


if __name__ == "__main__":
    main()
