// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>
//
// NOTE (hand-completion pass): the generated JSON only carried XEFOK and X412B.
// The remaining XEF* members below were added by hand from the authoritative
// version-L symbol files, which DO contain the whole XMFIDO status family:
//   F:\ND\SINTRAN-K05-XMSG-2026\XMSG-Symb\XMSG-VALUES-L.SYMB     (SYMBOL ...)
//   F:\ND\SINTRAN-K05-XMSG-2026\XMSG-Symb\XMSG-PL-VALUES-L.INCL  (CONSTANT ...)
// Those files are in DECIMAL (the .SYMB switches to @DEC at the top and back to
// @OCT at the end), so X412B = 17024 decimal = 41200 octal. All XEF* values are
// literal "n+X412B" in the source and are expanded to decimal here.

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// XMFIDO file-distribution status codes.
    /// </summary>
    public enum XmfidoStatus : int
    {
        /// <summary>
        /// Ok.
        /// </summary>
        XEFOK = 0,

        /// <summary>
        /// Base for this error range 41200B
        /// </summary>
        X412B = 17024,

        /// <summary>
        /// XEFCL: Watched port closed. (0+X412B)
        /// </summary>
        /// <remarks>
        /// Shares the value of <see cref="X412B"/> (17024 decimal = 41200 octal).
        /// </remarks>
        XEFCL = 0 + 17024,

        /// <summary>
        /// XEFSU: System connection up. (1+X412B)
        /// </summary>
        XEFSU = 1 + 17024,

        /// <summary>
        /// XEFSD: System connection down. (2+X412B)
        /// </summary>
        XEFSD = 2 + 17024,

        /// <summary>
        /// XEFTO: Timeout on request. (No answer from remote XMFIDO) (3+X412B)
        /// </summary>
        XEFTO = 3 + 17024,

        /// <summary>
        /// XEFAR: Start service for this port is already requested. (4+X412B)
        /// </summary>
        XEFAR = 4 + 17024,

        /// <summary>
        /// XEFIP: Illegal parameters. (5+X412B)
        /// </summary>
        XEFIP = 5 + 17024,

        /// <summary>
        /// XEFOV: Time parameter outside legal values. (6+X412B)
        /// </summary>
        XEFOV = 6 + 17024,

        /// <summary>
        /// XEFNP: No corresponding port found. (7+X412B)
        /// </summary>
        XEFNP = 7 + 17024,

        /// <summary>
        /// XEFIE: Internal error in XMFIDO. (8+X412B)
        /// </summary>
        XEFIE = 8 + 17024,

        /// <summary>
        /// XEFLT: Local XMFIDO is terminating. (9+X412B)
        /// </summary>
        XEFLT = 9 + 17024,

        /// <summary>
        /// XEFRT: Remote XMFIDO has terminated. (10+X412B)
        /// </summary>
        XEFRT = 10 + 17024,

        /// <summary>
        /// XEFRU: Table resources used up in XMFIDO. (11+X412B)
        /// </summary>
        /// <remarks>
        /// Wording differs between the two symbol files: XMSG-PL-VALUES-L.INCL says
        /// "Table resources used up in XMFIDO." while XMSG-VALUES-L.SYMB says
        /// "Table resources used in XMFIDO." (no "up"). The value is the same in both.
        /// </remarks>
        XEFRU = 11 + 17024,
    }
}
