// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// XMFIDO file-distribution status codes.
    /// </summary>
    public enum XmfidoStatus : int
    {
        /// <summary>
        /// Ok.
        /// </summary>
        XEFOK = 0,

        /// <summary>
        /// Base for this error range 41200B
        /// </summary>
        X412B = 17024,
    }
}
