// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// XMSG function codes (XF*) placed in the MON 200B T-register low byte.
    /// </summary>
    public enum XmsgFunction : int
    {
        /// <summary>
        /// Dummy function
        /// </summary>
        XFDUM = 0,

        /// <summary>
        /// Disconnect from message system
        /// </summary>
        XFDCT = 1,

        /// <summary>
        /// Get message space
        /// </summary>
        XFGET = 2,

        /// <summary>
        /// Release message space
        /// </summary>
        XFREL = 3,

        /// <summary>
        /// Read header from a message (6 bytes)
        /// </summary>
        XFRHD = 4,

        /// <summary>
        /// Write header to a message (6 bytes)
        /// </summary>
        XFWHD = 5,

        /// <summary>
        /// Read from message to user buffer
        /// </summary>
        XFREA = 6,

        /// <summary>
        /// Write from user to message
        /// </summary>
        XFWRI = 7,

        /// <summary>
        /// Set current message
        /// </summary>
        XFSCM = 8,

        /// <summary>
        /// Get message status
        /// </summary>
        XFMST = 9,

        /// <summary>
        /// Open port
        /// </summary>
        XFOPN = 10,

        /// <summary>
        /// Close port
        /// </summary>
        XFCLS = 11,

        /// <summary>
        /// Send message to a remote port
        /// </summary>
        XFSND = 12,

        /// <summary>
        /// Receive a message on a given port
        /// </summary>
        XFRCV = 13,

        /// <summary>
        /// Get local port status
        /// </summary>
        XFPST = 14,

        /// <summary>
        /// General status or wait
        /// </summary>
        XFGST = 15,

        /// <summary>
        /// Service initialisation function (privileged)
        /// </summary>
        XFSIN = 16,

        /// <summary>
        /// Service release function (obsolete)
        /// </summary>
        XFSRL = 17,

        /// <summary>
        /// Absolute read block from XMSG area (privileged)
        /// </summary>
        XFABR = 18,

        /// <summary>
        /// Absolute write block to XMSG area (obsolete)
        /// </summary>
        XFABW = 19,

        /// <summary>
        /// Lock message system (obsolete)
        /// </summary>
        XFMLK = 20,

        /// <summary>
        /// Unlock message system (obsolete)
        /// </summary>
        XFMUL = 21,

        /// <summary>
        /// Magic number to system number and port id.
        /// </summary>
        XFM2P = 22,

        /// <summary>
        /// Port to magic number
        /// </summary>
        XFP2M = 23,

        /// <summary>
        /// Routing initialise (obsolete)
        /// </summary>
        XFRIN = 24,

        /// <summary>
        /// Create driver with context (privileged)
        /// </summary>
        XFCRD = 25,

        /// <summary>
        /// Start driver (privileged)
        /// </summary>
        XFSTD = 26,

        /// <summary>
        /// Define indirect buffer (obsolete)
        /// </summary>
        XFDIB = 27,

        /// <summary>
        /// Read from indirect buffer (obsolete)
        /// </summary>
        XFRIB = 28,

        /// <summary>
        /// Write to indirect buffer (obsolete)
        /// </summary>
        XFWIB = 29,

        /// <summary>
        /// Request privilege
        /// </summary>
        XFPRV = 30,

        /// <summary>
        /// Write word 0 and return message
        /// </summary>
        XFRTN = 31,

        /// <summary>
        /// Receive message and read word 0
        /// </summary>
        XFRRH = 32,

        /// <summary>
        /// Define user buffer area for current message (privileged)
        /// </summary>
        XFDUB = 33,

        /// <summary>
        /// Define wake-up context (drivers only!)
        /// </summary>
        XFWDF = 34,

        /// <summary>
        /// Define bank no (drivers only)
        /// </summary>
        XFDBK = 35,

        /// <summary>
        /// Start multi-function call
        /// </summary>
        XFSMC = 36,

        /// <summary>
        /// Define max memory for a task (privileged)
        /// </summary>
        XFDMM = 37,

        /// <summary>
        /// Allocate messages to a task
        /// </summary>
        XFALM = 38,

        /// <summary>
        /// Free allocated messages
        /// </summary>
        XFFRM = 39,

        /// <summary>
        /// List messages and ports
        /// </summary>
        XFLMP = 40,

        /// <summary>
        /// Receive and read message
        /// </summary>
        XFRRE = 41,

        /// <summary>
        /// Check system and/or user privileges
        /// </summary>
        XFCPV = 42,

        /// <summary>
        /// Write and return message
        /// </summary>
        XFWRT = 43,

        /// <summary>
        /// Modify routing tables (privileged - COSROUT only!)
        /// </summary>
        XFMRT = 44,

        /// <summary>
        /// Send message via specified link/netserver (priv - COSROUT only!)
        /// </summary>
        XFSFM = 45,

        /// <summary>
        /// Cosrout receive and read message (priv - COSROUT only!)
        /// </summary>
        XFCRR = 46,

        /// <summary>
        /// General status multiple or wait
        /// </summary>
        XFGSM = 47,
    }
}
