// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// XMSG user error codes (XE*), returned negative in the T-register.
    /// </summary>
    public enum XmsgError : int
    {
        /// <summary>
        /// XMSG crash (Info in Basefield)
        /// </summary>
        XECRA = -63,

        /// <summary>
        /// Function not available to tasks other than COSROUT
        /// </summary>
        XEICM = -44,

        /// <summary>
        /// Network checksum error (purely internal significance)
        /// </summary>
        XENCE = -43,

        /// <summary>
        /// Too many multi-call functions
        /// </summary>
        XETMU = -42,

        /// <summary>
        /// Driver called XMSG with illegal XT-block
        /// </summary>
        XEIXT = -41,

        /// <summary>
        /// Network remote reject (request retransmit)
        /// </summary>
        XEREJ = -40,

        /// <summary>
        /// No user segment info defined (XFUSG option)
        /// </summary>
        XENUS = -39,

        /// <summary>
        /// Timeout detected by network layer
        /// </summary>
        XENTO = -38,

        /// <summary>
        /// XMSG not running === do not move - used in SINTRAN ===
        /// </summary>
        XENRU = -37,

        /// <summary>
        /// Remote port closed while message queued
        /// </summary>
        XEPCL = -36,

        /// <summary>
        /// Remote system not defined
        /// </summary>
        XERND = -35,

        /// <summary>
        /// Network sequencing error (purely internal significance)
        /// </summary>
        XENSE = -34,

        /// <summary>
        /// Indirect Buffer not on valid segment
        /// </summary>
        XENOS = -33,

        /// <summary>
        /// Illegal use of reentrant segment in XFDIB
        /// </summary>
        XEILR = -32,

        /// <summary>
        /// Illegal displacement in read/write
        /// </summary>
        XEIDP = -31,

        /// <summary>
        /// Illegal transfer length for read/write
        /// </summary>
        XEITL = -30,

        /// <summary>
        /// No port open (so 'default port' param invalid)
        /// </summary>
        XENDP = -29,

        /// <summary>
        /// Driver called XMSG before return from previous
        /// </summary>
        XEDRI = -28,

        /// <summary>
        /// Message already has XMSG buffer (XFDUB)
        /// </summary>
        XEXBF = -27,

        /// <summary>
        /// Remote task space overflow
        /// </summary>
        XEROV = -26,

        /// <summary>
        /// Remote system not available
        /// </summary>
        XERNA = -25,

        /// <summary>
        /// Privilege request refused
        /// </summary>
        XEPVR = -24,

        /// <summary>
        /// Privileged function called without privilege.
        /// </summary>
        XEPRV = -23,

        /// <summary>
        /// Illegal port number
        /// </summary>
        XEIPN = -22,

        /// <summary>
        /// Illegal message size or not enough space left
        /// </summary>
        XEILM = -21,

        /// <summary>
        /// Message space full or buffer not available
        /// </summary>
        XEMFL = -20,

        /// <summary>
        /// Invalid magic number
        /// </summary>
        XEIMA = -19,

        /// <summary>
        /// Illegal function code
        /// </summary>
        XEILF = -18,

        /// <summary>
        /// No Valid Indirect buffer defined
        /// </summary>
        XENVI = -17,

        /// <summary>
        /// Write Not Allowed (Indirect buffer)
        /// </summary>
        XEWNA = -16,

        /// <summary>
        /// Return of a bounce message
        /// </summary>
        XEBNC = -15,

        /// <summary>
        /// XMSG Kernel already initialised
        /// </summary>
        XEAIN = -14,

        /// <summary>
        /// Message is in a queue.
        /// </summary>
        XEBFC = -13,

        /// <summary>
        /// Message is already chained
        /// </summary>
        XEMCH = -12,

        /// <summary>
        /// No default message
        /// </summary>
        XENDM = -11,

        /// <summary>
        /// Function not available to drivers
        /// </summary>
        XEIDR = -10,

        /// <summary>
        /// No more ports available
        /// </summary>
        XENOP = -9,

        /// <summary>
        /// Illegal function for RT-programs (only drivers)
        /// </summary>
        XEIRT = -8,

        /// <summary>
        /// Message buffer not yours
        /// </summary>
        XEBNY = -7,

        /// <summary>
        /// Illegal message buffer pointer
        /// </summary>
        XEIBP = -6,

        /// <summary>
        /// Facility not yet implemented
        /// </summary>
        XENIM = -5,

        /// <summary>
        /// Task is not allowed any more memory
        /// </summary>
        XETMM = -4,

        /// <summary>
        /// Network layer initialization reject (purely internal)
        /// </summary>
        XENIR = -3,

        /// <summary>
        /// Non-local remote port illegal here
        /// </summary>
        XEIRM = -2,

        /// <summary>
        /// No more XT-blocks free
        /// </summary>
        XENOT = -1,

        /// <summary>
        /// Base for standard error system (41000B)
        /// </summary>
        XKXXX = 16896,
    }
}
