// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// MON 200B T-register option bits, OR-ed into the high-order byte alongside
    /// the function code. Each flag mask is <c>1 shifted left bit</c>.
    /// </summary>
    [System.Flags]
    public enum XmsgOption : ushort
    {
        /// <summary>
        /// No option bits set.
        /// </summary>
        None = 0,

        /// <summary>
        /// Bit set to indicate system mode call (system domain).
        /// </summary>
        /// <remarks>
        /// Bit 7 (mask 0x0080) in the MON 200B T-register high byte.
        /// </remarks>
        XFSYS = 1 << 7,

        /// <summary>
        /// In XFSND/SFM: Send task current message
        /// </summary>
        /// <remarks>
        /// Bit 8 (mask 0x0100) in the MON 200B T-register high byte.
        /// </remarks>
        XFTCM = 1 << 8,

        /// <summary>
        /// In XFSND/RTN/WRT: Secure message (Return if not deliv'd).
        /// </summary>
        /// <remarks>
        /// Bit 9 (mask 0x0200) in the MON 200B T-register high byte.
        /// </remarks>
        XFSEC = 1 << 9,

        /// <summary>
        /// In XFWRT: Reset the current message displacement to 0.
        /// </summary>
        /// <remarks>
        /// Bit 10 (mask 0x0400) in the MON 200B T-register high byte.
        /// </remarks>
        XFRDI = 1 << 10,

        /// <summary>
        /// In XFSND: Message to be sent to XROUT (see XFRRO).
        /// </summary>
        /// <remarks>
        /// Bit 10 (mask 0x0400) in the MON 200B T-register high byte.
        /// </remarks>
        XFROU = 1 << 10,

        /// <summary>
        /// In XFSND/RTN/WRT/SFM: Forward message.
        /// </summary>
        /// <remarks>
        /// Bit 11 (mask 0x0800) in the MON 200B T-register high byte.
        /// </remarks>
        XFFWD = 1 << 11,

        /// <summary>
        /// In XFSND/RTN/WRT: Bounce message.
        /// </summary>
        /// <remarks>
        /// Bit 12 (mask 0x1000) in the MON 200B T-register high byte.
        /// </remarks>
        XFBNC = 1 << 12,

        /// <summary>
        /// In XFWRI: Reset message length to 0 before data is written.
        /// </summary>
        /// <remarks>
        /// Bit 12 (mask 0x1000) in the MON 200B T-register high byte.
        /// </remarks>
        XFRES = 1 << 12,

        /// <summary>
        /// In XFRRE: Release the message if the last byte is read.
        /// </summary>
        /// <remarks>
        /// Bit 12 (mask 0x1000) in the MON 200B T-register high byte.
        /// </remarks>
        XFRMR = 1 << 12,

        /// <summary>
        /// In XFALM/GET: Allocate/reserve exclusive message buffer(s).
        /// </summary>
        /// <remarks>
        /// Bit 13 (mask 0x2000) in the MON 200B T-register high byte.
        /// </remarks>
        XFEXC = 1 << 13,

        /// <summary>
        /// In XFSND/RTN/WRT/SFM: If not XFROU then high-priority message
        /// </summary>
        /// <remarks>
        /// Bit 13 (mask 0x2000) in the MON 200B T-register high byte.
        /// </remarks>
        XFHIP = 1 << 13,

        /// <summary>
        /// In XFSTD: Driver to run with paging on.
        /// </summary>
        /// <remarks>
        /// Bit 13 (mask 0x2000) in the MON 200B T-register high byte.
        /// </remarks>
        XFPON = 1 << 13,

        /// <summary>
        /// In XFSND: If XFROU then non-local XROUT (sysno in A-reg).
        /// </summary>
        /// <remarks>
        /// Bit 13 (mask 0x2000) in the MON 200B T-register high byte.
        /// </remarks>
        XFRRO = 1 << 13,

        /// <summary>
        /// In XFRCV/PST/GST/RRH/RRE: Wake up task on status change.
        /// </summary>
        /// <remarks>
        /// Bit 14 (mask 0x4000) in the MON 200B T-register high byte.
        /// </remarks>
        XFWAK = 1 << 14,

        /// <summary>
        /// If set then wait if operation not terminated.
        /// </summary>
        /// <remarks>
        /// Bit 15 (mask 0x8000) in the MON 200B T-register high byte.
        /// </remarks>
        XFWTF = 1 << 15,
    }
}
