// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// Message-type codes (XM*) returned by XFRCV in the T-register.
    /// </summary>
    public enum XmsgMessageType : int
    {
        /// <summary>
        /// Normal message
        /// </summary>
        XMTNO = 1,

        /// <summary>
        /// Routed message (Via XROUT)
        /// </summary>
        XMROU = 2,

        /// <summary>
        /// High priority message
        /// </summary>
        XMTHI = 3,

        /// <summary>
        /// Return message (Abnormal condition)
        /// </summary>
        XMTRE = 4,

        /// <summary>
        /// XROUT has been kicked (no message)
        /// </summary>
        XMKIK = 5,

        /// <summary>
        /// Pseudo message (not used)
        /// </summary>
        XMTPS = 6,
    }
}
