// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// XMSG driver-interface functions (XD*, DRXMSG).
    /// </summary>
    public enum XmsgDriverFunction : int
    {
        /// <summary>
        /// Get message info
        /// </summary>
        XDINF = 1,

        /// <summary>
        /// Set byte pointer
        /// </summary>
        XDSBP = 2,

        /// <summary>
        /// Put byte sequential
        /// </summary>
        XDPUS = 3,

        /// <summary>
        /// Put byte random
        /// </summary>
        XDPUR = 4,

        /// <summary>
        /// Get byte sequential
        /// </summary>
        XDGES = 5,

        /// <summary>
        /// Get byte random
        /// </summary>
        XDGER = 6,
    }
}
