// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// XMSG kernel crash codes (XX*).
    /// </summary>
    public enum XmsgCrashCode : int
    {
        /// <summary>
        /// Illegal port address in the creation of magic number
        /// </summary>
        XXEIE = 1,

        /// <summary>
        /// Illegal owner of buffer
        /// </summary>
        XXIOW = 2,

        /// <summary>
        /// Memory allocation inconsistency
        /// </summary>
        XXBIN = 3,

        /// <summary>
        /// Message queue length inconsistency
        /// </summary>
        XXMCE = 4,

        /// <summary>
        /// ZRALL gave port not in XQTAB (Not used)
        /// </summary>
        XXIEN = 5,

        /// <summary>
        /// XROUT: ZFUNC function &gt;X5FUN
        /// </summary>
        XXIFL = 6,

        /// <summary>
        /// Illegal RT-Description add used (Not used)
        /// </summary>
        XXIRT = 7,

        /// <summary>
        /// INIT: No Buffer space available (Not used)
        /// </summary>
        XXNBF = 8,

        /// <summary>
        /// Inconsistency in resource allocation
        /// </summary>
        XXRIN = 9,

        /// <summary>
        /// More memory released than owned
        /// </summary>
        XXNMM = 10,

        /// <summary>
        /// Not implemented (Cannot recover) (Not used)
        /// </summary>
        XXNIM = 11,

        /// <summary>
        /// Inconsistency in port chain when closing
        /// </summary>
        XXCLS = 12,

        /// <summary>
        /// Double chaining attempted
        /// </summary>
        XXCHE = 13,

        /// <summary>
        /// No XMSG-RESIDENT found by initialization (Not used)
        /// </summary>
        XXNOR = 14,

        /// <summary>
        /// Inconsistency in XMPRT/XPCMS Pair
        /// </summary>
        XXICM = 15,

        /// <summary>
        /// This can only be done on N100'S (Not used)
        /// </summary>
        XX100 = 16,

        /// <summary>
        /// Inconsistency in level 5 monitor queues
        /// </summary>
        XXMON = 17,

        /// <summary>
        /// Multisystem XMSG not implemented/generated (Not used)
        /// </summary>
        XXMMC = 18,

        /// <summary>
        /// Frame buffer handling inconsistency
        /// </summary>
        XXFBI = 19,

        /// <summary>
        /// Protocol error in communications system
        /// </summary>
        XXPER = 20,

        /// <summary>
        /// Illegal LOG NO for HDLC (bad LOGPH) (Not used)
        /// </summary>
        XXILN = 21,

        /// <summary>
        /// No legal routing (XROUT) port defined
        /// </summary>
        XXROU = 22,

        /// <summary>
        /// Error in HDLC Driver or interface to it
        /// </summary>
        XXHER = 23,

        /// <summary>
        /// XROUT fatal error - see XROUT Basefield
        /// </summary>
        XXRO2 = 24,

        /// <summary>
        /// Task handling (wait,resume) error
        /// </summary>
        XXTAS = 25,

        /// <summary>
        /// Message handling error (kernel-net interface)
        /// </summary>
        XXMER = 26,

        /// <summary>
        /// Network gateway error
        /// </summary>
        XXNER = 27,

        /// <summary>
        /// No legal COSMOS routing manager port defined
        /// </summary>
        XXCRM = 28,

        /// <summary>
        /// Inconsistency in COSMOS routing manager
        /// </summary>
        XXRIC = 29,

        /// <summary>
        /// Gateway code not generated (Not used)
        /// </summary>
        XXNGA = 30,

        /// <summary>
        /// XROUT: Resource inconsistency
        /// </summary>
        XXRI2 = 31,

        /// <summary>
        /// XROUT: Releasing invalid name unit
        /// </summary>
        XXINP = 32,

        /// <summary>
        /// XROUT: Buffer handling error (xb... routines)
        /// </summary>
        XXBER = 33,

        /// <summary>
        /// XROUT: Response with no request outstanding (Not used)
        /// </summary>
        XXRUT = 34,

        /// <summary>
        /// XROUT: No multi-system xmsg - inconsistent! (Not used)
        /// </summary>
        XXNXM = 35,

        /// <summary>
        /// XROUT: Not loaded correctly with RT loader
        /// </summary>
        XXNLD = 36,

        /// <summary>
        /// XROUT: Stopped by 'STOP-XMSG' in SINTRAN-SERVICE (Not used)
        /// </summary>
        XXUSR = 37,

        /// <summary>
        /// XROUT: 8X100 library mark set, but this is ND-10 (Not used)
        /// </summary>
        XXN10 = 38,

        /// <summary>
        /// XROUT: No space available for fixing tables and/or message area
        /// </summary>
        XXNSG = 39,

        /// <summary>
        /// XROUT: Not yet implemented (Not used)
        /// </summary>
        XXNI2 = 40,

        /// <summary>
        /// XROUT: System / routing table inconsistency
        /// </summary>
        XXMIN = 41,

        /// <summary>
        /// XROUT: Table allocation inconsistency
        /// </summary>
        XXTAI = 42,

        /// <summary>
        /// XROUT: Wrong SINTRAN III SYMBOL--LISTs
        /// </summary>
        XXWS3 = 43,

        /// <summary>
        /// XROUT: Not enough space for seg 33 (or too big)
        /// </summary>
        XXN33 = 44,

        /// <summary>
        /// XROUT: PIT3 version must run on S3 version I or later
        /// </summary>
        XXVSX = 45,

        /// <summary>
        /// XROUT: CX version must run on a ND-100/CX or a ND-110
        /// </summary>
        XXNCX = 46,

        /// <summary>
        /// XROUT: Not generated for this system
        /// </summary>
        XXWSY = 47,

        /// <summary>
        /// XROUT: Length of system/port names too long, reduce length of name
        /// </summary>
        XXMNL = 48,

        /// <summary>
        /// XROUT: Not allowed on this system (error from MON CPUST/ENTSG)
        /// </summary>
        XXILL = 50,

        /// <summary>
        /// XROUT: Kernel tables are too big, reduce system parameters
        /// </summary>
        XXKTB = 51,

        /// <summary>
        /// XROUT: XMSG is not initialized to SINTRAN.
        /// </summary>
        XXNIN = 52,

        /// <summary>
        /// XROUT: Too many systems, reduce max number of systems accessible
        /// </summary>
        XXNSA = 53,

        /// <summary>
        /// XROUT: Too many named ports, reduce max number of named ports
        /// </summary>
        XXNNP = 54,

        /// <summary>
        /// XROUT: XMSG is not generated correctly
        /// </summary>
        XXILG = 55,

        /// <summary>
        /// XROUT: Physical tables are too big (&gt;64K)
        /// </summary>
        XXTBT = 56,

        /// <summary>
        /// XROUT: Message buffer pool is too big (&gt;256K)
        /// </summary>
        XXTBM = 57,
    }
}
