// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// Sub-service codes (parameter 1) for the XSDAT define/remove-attribute service.
    /// </summary>
    public enum XroutDefineAttributeSubservice : int
    {
        /// <summary>
        /// Define friend system
        /// </summary>
        XSDFR = 1,

        /// <summary>
        /// Remove friend system
        /// </summary>
        XSRFR = 2,

        /// <summary>
        /// Enable checksum
        /// </summary>
        XSECS = 3,

        /// <summary>
        /// Disable checksum
        /// </summary>
        XSDCS = 4,

        /// <summary>
        /// Define alternative link (COSROUT only)
        /// </summary>
        XSDAL = 5,
    }
}
