// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// Sub-service codes (parameter 1) for the XSSCI set-crash-information service.
    /// </summary>
    public enum XroutSetCrashInfoSubservice : int
    {
        /// <summary>
        /// Enable/disable auto-restart of XMSG
        /// </summary>
        XSDAR = 1,

        /// <summary>
        /// Define/remove restart-files
        /// </summary>
        XSDRF = 2,

        /// <summary>
        /// Define/remove dump-files
        /// </summary>
        XSDDF = 3,

        /// <summary>
        /// Get defined dump-files
        /// </summary>
        XSGDF = 4,

        /// <summary>
        /// Dump XMSG onto files
        /// </summary>
        XSDUX = 5,

        /// <summary>
        /// Get defined restart-files
        /// </summary>
        XSGRF = 6,

        /// <summary>
        /// Get auto-restart definition
        /// </summary>
        XSGAR = 7,
    }
}
