// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// XROUT service codes (XS*), byte 1 of the standard-message header.
    /// </summary>
    /// <remarks>
    /// From XMSG-PL-VALUES-L.INCL / XMSG-VALUES-L.SYMB, section
    /// "XROUT - SERVICE VALUES": "Values in byte 1 of message. Bit 6 is set
    /// => service request".
    /// The matching error section says: "Error values returned in byte 1 of
    /// return message (Bit 6 reset)". So bit 6 (value 64) of byte 1 is what
    /// tells a service REQUEST apart from an error REPLY: set means request,
    /// reset means error code. That is why every service value here starts at
    /// 64 (XSNUL) - the low 6 bits carry the service number.
    /// Values in the ND symbol files are DECIMAL, not octal (the .SYMB is
    /// bracketed by @DEC ... @OCT and carries the warning "This file is now in
    /// DECIMAL to keep PLANC happy!"). The values below are decimal.
    /// </remarks>
    public enum XroutService : int
    {
        /// <summary>
        /// Null command returns 0 status to sender
        /// </summary>
        XSNUL = 64,

        /// <summary>
        /// Send a letter
        /// </summary>
        XSLET = 65,

        /// <summary>
        /// Give name to this port
        /// </summary>
        XSNAM = 66,

        /// <summary>
        /// Clear name of this port
        /// </summary>
        XSCNM = 67,

        /// <summary>
        /// Get name of port (param: MAGNO)
        /// </summary>
        XSGNM = 68,

        /// <summary>
        /// Get name (param: MC/PORTNO)
        /// </summary>
        XSGNI = 69,

        /// <summary>
        /// XSRME get remote magic number (params: LOC, REM NAME, MC).
        /// </summary>
        /// <remarks>
        /// <para><b>Added 2026-08-06 - the M include leaves 70 and 72 unnamed</b></para>
        /// This enum used to jump from 69 straight to 71, because
        /// <c>XMSG-PL-VALUES-M.INCL</c> and <c>XMSG-VALUES-M.SYMB</c> both skip the two codes.
        /// The OLDER Communication Guide names them:
        /// <code>
        /// ND-60.134.2 EN SINTRAN III Communication Guide.md:4766   XSRME= 106  Get remote magic number (LOC, REM NAME, MC)
        /// </code>
        /// <c>106</c> octal = 70. Described at section 4.4.2.9 (line 2179): it asks the LOCAL XROUT
        /// to fetch a remote port's magic number and enter it in its own tables. The number is NOT
        /// returned to the caller - the point is the cache, not the answer.
        /// <para>
        /// This is an XROUT-to-XROUT service. A real multi-system dialogue uses it, so if a live
        /// D100 XROUT sends one we should at least be able to NAME the service byte.
        /// </para>
        /// <para>
        /// Whether revision M dropped it or merely omits it from the include is UNKNOWN - the M
        /// symbol table does not list it either, and no M-generation XROUT disassembly has been read
        /// that would settle it. Declared because naming an observed byte beats decoding it as
        /// unknown; nothing sends it.
        /// </para>
        /// </remarks>
        XSRME = 70,

        /// <summary>
        /// Get magic number from name (privileged)
        /// </summary>
        XSGMG = 71,

        /// <summary>
        /// XSCMG clear magic number (privileged).
        /// </summary>
        /// <remarks>
        /// The other code the M include leaves unnamed:
        /// <code>
        /// ND-60.134.2 EN SINTRAN III Communication Guide.md:4768   XSCMG= 110  Clear magic number (PRIV)
        /// </code>
        /// <c>110</c> octal = 72. Described at section 4.4.2.11 (line 2200): XROUT-to-XROUT, "this
        /// magic number is no longer valid", sent when a local port closes. It is the invalidation
        /// that answers <see cref="XSRME"/>'s caching - the two are a pair.
        /// <para>
        /// Same UNKNOWN as <see cref="XSRME"/> about why M omits it.
        /// </para>
        /// </remarks>
        XSCMG = 72,

        /// <summary>
        /// Define remote name (privileged)
        /// </summary>
        XSDRN = 73,

        /// <summary>
        /// Define routing for system N - old symbol (alias of XSDSY)
        /// </summary>
        XSDMC = 74,

        /// <summary>
        /// Define routing for system N (privileged)
        /// </summary>
        XSDSY = 74,

        /// <summary>
        /// Get routing info for system N - old symbol (alias of XSGSY)
        /// </summary>
        XSGMC = 75,

        /// <summary>
        /// Get routing info for system N
        /// </summary>
        XSGSY = 75,

        /// <summary>
        /// Start up specified link (privileged)
        /// </summary>
        XSLKI = 76,

        /// <summary>
        /// Initialise tracing (open file, ..) (privileged)
        /// </summary>
        XSTIN = 77,

        /// <summary>
        /// Close tracing (privileged)
        /// </summary>
        XSTCL = 78,

        /// <summary>
        /// Define tracing conditions (privileged)
        /// </summary>
        XSTDC = 79,

        /// <summary>
        /// Create service (name, init no of SP's)
        /// </summary>
        XSCRS = 80,

        /// <summary>
        /// New service point(s) (increment/decrement in SP's)
        /// </summary>
        XSNSP = 81,

        /// <summary>
        /// Get information about name
        /// </summary>
        XSGIN = 82,

        /// <summary>
        /// Define local system (privileged)
        /// </summary>
        XSDLO = 83,

        /// <summary>
        /// Send letter and kick if unavailable (privileged)
        /// </summary>
        /// <remarks>
        /// Second comment line from both symbol files: "When COSROUT is
        /// running: XSLEK is not available".
        /// </remarks>
        XSLEK = 84,

        /// <summary>
        /// Start/stop gateway (network server) (privileged)
        /// </summary>
        XSNET = 85,

        /// <summary>
        /// Set crash information (privileged)
        /// </summary>
        XSSCI = 86,

        /// <summary>
        /// Get/check attribute
        /// </summary>
        XSGAT = 87,

        /// <summary>
        /// Define/remove attribute (privileged)
        /// </summary>
        XSDAT = 88,

        /// <summary>
        /// Get network server information (privileged)
        /// </summary>
        XSNSI = 89,

        /// <summary>
        /// Get information about a link (privileged)
        /// </summary>
        XSLIN = 90,

        /// <summary>
        /// Get information about named ports
        /// </summary>
        XSPIN = 91,

        /// <summary>
        /// Get information about a system (privileged)
        /// </summary>
        XSLSY = 92,

        /// <summary>
        /// Get info about system utilization (privileged)
        /// </summary>
        XSGSU = 93,

        /// <summary>
        /// Start/stop Cosmos routing manager (priv - COSROUT only!)
        /// </summary>
        XSCRM = 94,

        /// <summary>
        /// Get information from link tables (priv - COSROUT only!)
        /// </summary>
        XSGLI = 95,

        /// <summary>
        /// Get info about system generation variables (privileged)
        /// </summary>
        XSGSG = 96,

        /// <summary>
        /// Maximum legal service value (alias of XSGSG)
        /// </summary>
        XSMAX = 96,
    }
}
