// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// XROUT / network-server error codes (XR*), byte 1 of a reply.
    /// </summary>
    public enum XroutError : int
    {
        /// <summary>
        /// OK - not an error!
        /// </summary>
        XRSOK = 0,

        /// <summary>
        /// Illegal service number
        /// </summary>
        XRISN = 1,

        /// <summary>
        /// Unknown name (of server or system)
        /// </summary>
        XRUNN = 2,

        /// <summary>
        /// Another port already has this name
        /// </summary>
        XRDDF = 3,

        /// <summary>
        /// No space left for names
        /// </summary>
        XRNSP = 4,

        /// <summary>
        /// Illegal parameter type
        /// </summary>
        XRIPT = 5,

        /// <summary>
        /// Missing mandatory parameter
        /// </summary>
        XRMMP = 6,

        /// <summary>
        /// Unknown magic number
        /// </summary>
        XRUNM = 7,

        /// <summary>
        /// Too short message or resulting message too long
        /// </summary>
        XRMTL = 8,

        /// <summary>
        /// Standard message format not handled
        /// </summary>
        XRSMF = 9,

        /// <summary>
        /// Caller was not privileged
        /// </summary>
        XRPRV = 10,

        /// <summary>
        /// Illegal system number parameter
        /// </summary>
        XRISY = 11,

        /// <summary>
        /// No access to remote system
        /// </summary>
        XRNRO = 12,

        /// <summary>
        /// Illegal integer value
        /// </summary>
        XRIIV = 13,

        /// <summary>
        /// Cannot define route to a neighbour
        /// </summary>
        XRNEI = 14,

        /// <summary>
        /// Invalid service request - not available to current caller
        /// </summary>
        XRNXM = 15,

        /// <summary>
        /// Illegal/Reserved Logical Unit Number (LUN) for link
        /// </summary>
        XRILN = 16,

        /// <summary>
        /// No more Link Descriptors (XL-blocks) for start-link/netserver
        /// </summary>
        XRNXL = 17,

        /// <summary>
        /// Not enough resources (XD/XF/XM-Blocks) for start-link/netserver
        /// </summary>
        XRNXD = 18,

        /// <summary>
        /// No trace generated (no trace buffer available)'
        /// </summary>
        XRNTR = 19,

        /// <summary>
        /// Trace already active
        /// </summary>
        XRTRA = 20,

        /// <summary>
        /// Trace passive
        /// </summary>
        XRTRP = 21,

        /// <summary>
        /// Trace/dump file open error (see parameter 1)
        /// </summary>
        XRTFE = 22,

        /// <summary>
        /// Trace RT-prog (XTRACE) not found
        /// </summary>
        XRTRT = 23,

        /// <summary>
        /// Illegal trace system number
        /// </summary>
        XRTIS = 24,

        /// <summary>
        /// Bad link - open unsuccessful
        /// </summary>
        XRBLK = 25,

        /// <summary>
        /// Attempt to redefine local system no
        /// </summary>
        XRSYD = 26,

        /// <summary>
        /// No local system number defined
        /// </summary>
        XRNLS = 27,

        /// <summary>
        /// Too many remote names to this system
        /// </summary>
        XRTRE = 28,

        /// <summary>
        /// Old service calls (below 64) cannot go remote
        /// </summary>
        XRRNA = 29,

        /// <summary>
        /// Service points busy
        /// </summary>
        XRBUS = 30,

        /// <summary>
        /// This is not a service port
        /// </summary>
        XRNSE = 31,

        /// <summary>
        /// Remote port statically declared
        /// </summary>
        XRRPN = 32,

        /// <summary>
        /// Unknown remote system name or number
        /// </summary>
        XRUKS = 33,

        /// <summary>
        /// Remote system message table space full
        /// </summary>
        XRMFL = 34,

        /// <summary>
        /// Remote task message space used up
        /// </summary>
        XRROV = 35,

        /// <summary>
        /// Routing table full (too many systems)
        /// </summary>
        XRRFU = 36,

        /// <summary>
        /// No remote batch service available
        /// </summary>
        XRNRB = 37,

        /// <summary>
        /// Unknown RT name
        /// </summary>
        XRURT = 38,

        /// <summary>
        /// This server is not running
        /// </summary>
        XRSNR = 39,

        /// <summary>
        /// Netserver: remote system is not defined
        /// </summary>
        XRRND = 40,

        /// <summary>
        /// Netserver: network not available
        /// </summary>
        XRNNA = 41,

        /// <summary>
        /// Netserver: internal server error
        /// </summary>
        XRISE = 42,

        /// <summary>
        /// Netserver: invalid request
        /// </summary>
        XRIRQ = 43,

        /// <summary>
        /// XMSG not congfigurated with gateway code
        /// </summary>
        XRNGA = 44,

        /// <summary>
        /// Remote system not on same LAN
        /// </summary>
        XRRNL = 45,

        /// <summary>
        /// No connection to this system (unknown status)
        /// </summary>
        XRNCO = 46,

        /// <summary>
        /// Ambiguous name
        /// </summary>
        XRAMB = 47,

        /// <summary>
        /// Friend system table full (too many friends)
        /// </summary>
        XRFFU = 48,

        /// <summary>
        /// Netserver: network temporarily not available
        /// </summary>
        XRNTA = 49,

        /// <summary>
        /// Netserver: message too old
        /// </summary>
        XRMTO = 50,

        /// <summary>
        /// COSMOS routing manager is not running
        /// </summary>
        XRCNR = 51,

        /// <summary>
        /// COSMOS routing manager is already running
        /// </summary>
        XRICR = 52,

        /// <summary>
        /// Routing information defined (start/stop inhibited)
        /// </summary>
        XRRID = 53,

        /// <summary>
        /// COSMOS routing manager: invalid request
        /// </summary>
        XRIRR = 54,

        /// <summary>
        /// XRILX - Illegal link number parameter.
        /// SOURCE DISCREPANCY: present in XMSG-PL-VALUES-L.INCL ("CONSTANT XRILX=55")
        /// but ABSENT from XMSG-VALUES-L.SYMB, whose XROUT error range stops at
        /// XRIRR=54. The M-version include file that generated this enum has it, so
        /// the value 55 is kept.
        /// </summary>
        XRILX = 55,

        /// <summary>
        /// Base for XROUT errors: 41100B
        /// </summary>
        XRXXX = 16960,
    }
}
