// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// Sub-service codes (parameter 1) for the XSDAT define/remove-attribute service.
    /// </summary>
    public enum XroutDefineAttributeSubservice : int
    {
        /// <summary>
        /// Define friend system
        /// </summary>
        XSDFR = 1,

        /// <summary>
        /// Remove friend system
        /// </summary>
        XSRFR = 2,

        /// <summary>
        /// Enable checksum
        /// </summary>
        XSECS = 3,

        /// <summary>
        /// Disable checksum
        /// </summary>
        XSDCS = 4,

        /// <summary>
        /// Define alternative link (COSROUT only)
        /// </summary>
        /// <remarks>
        /// Minor wording discrepancy: XMSG-PL-VALUES-L.INCL says "Define
        /// alternative link (COSROUT only)"; XMSG-VALUES-L.SYMB line 241 says
        /// only "Define alternative link" without the COSROUT qualifier.
        /// Same value (5) in both.
        /// </remarks>
        XSDAL = 5,

        /// <summary>
        /// Set route through flag
        /// </summary>
        /// <remarks>
        /// DISCREPANCY between the two authoritative ND symbol files:
        /// XMSG-VALUES-L.SYMB line 242 has "SYMBOL XSSRT=6     % Set route
        /// through flag", but XMSG-PL-VALUES-L.INCL has no XSSRT at all - its
        /// XSDAT sub-service list stops at XSDAL=5. Included here because the
        /// .SYMB (the assembler symbol file the running XMSG was built with)
        /// defines it.
        /// </remarks>
        XSSRT = 6,
    }
}
