// <auto-generated>
// Generated from SINTRAN/XMSG/xmsg-constants.json (XMSG version M, 1988-08-18).
// Source include file: SINTRAN/XMSG/XMSG-PL-VALUES-M.INCL
// Descriptions are copied verbatim from the official ND include-file comments.
// Do not edit by hand - regenerate from the JSON.
// </auto-generated>

namespace NDInsight.Sintran.Xmsg
{

    /// <summary>
    /// Sub-service codes (parameter 1) for the XSGAT get/check-attribute service.
    /// </summary>
    public enum XroutGetAttributeSubservice : int
    {
        /// <summary>
        /// Get XMSG version and revision
        /// </summary>
        XSGXV = 1,

        /// <summary>
        /// Check magic number
        /// </summary>
        XSCMG = 2,

        /// <summary>
        /// Get complete system or port name (deabbreviate name)
        /// </summary>
        XSGCN = 3,

        /// <summary>
        /// Get friend information (privileged!)
        /// </summary>
        XSGFR = 4,

        /// <summary>
        /// Get local system number and name
        /// </summary>
        XSGLO = 5,
    }
}
